use crate::{audit::{self,AuditRecord},auth,execute_named,now_secs,output_hash,CLOUDOS_ROOT};
use axum::{extract::State,http::{HeaderMap,StatusCode},response::IntoResponse,routing::{get,post},Json,Router};
use serde::{Deserialize,Serialize};
use std::{collections::HashMap,net::{IpAddr,SocketAddr},path::PathBuf,sync::{Arc,Mutex}};
use uuid::Uuid;
#[derive(Clone)]pub struct GatewayState{pub secret:String,pub server:String,pub audit_path:PathBuf,pub replay:Arc<Mutex<HashMap<String,u64>>>}
#[derive(Deserialize)]struct ExecuteRequest{protocol:String,request_id:String,timestamp:u64,nonce:String,principal:String,operation:String,root:Option<String>}
#[derive(Serialize)]struct ExecuteResponse{request_id:String,success:bool,exit_code:Option<i32>,output:String,audit_hash:String}
pub async fn serve(bind:&str,state:GatewayState)->Result<(),String>{let addr:SocketAddr=bind.parse().map_err(|_|"invalid gateway bind")?;if !matches!(addr.ip(),IpAddr::V4(v) if v.is_loopback())&&!matches!(addr.ip(),IpAddr::V6(v) if v.is_loopback()){return Err("gateway must bind to loopback; terminate TLS/authenticated transport in front of it".into())}let app=Router::new().route("/v1/health",get(health)).route("/v1/execute",post(execute)).route("/v1/audit",get(audit_log)).with_state(state);let listener=tokio::net::TcpListener::bind(addr).await.map_err(|e|e.to_string())?;axum::serve(listener,app).await.map_err(|e|e.to_string())}
async fn health()->impl IntoResponse{Json(serde_json::json!({"ok":true,"protocol":"KMJ-COMMANDER/1","auth":"short-lived-hmac","policy":"deny-by-default"}))}
fn authenticate(headers:&HeaderMap,state:&GatewayState,scope:&str)->Result<auth::TokenClaims,(StatusCode,String)>{let h=headers.get("authorization").and_then(|v|v.to_str().ok());let c=auth::verify_bearer(h,&state.secret,now_secs(),&state.server).map_err(|e|(StatusCode::UNAUTHORIZED,e))?;if !c.scopes.iter().any(|s|s==scope){return Err((StatusCode::FORBIDDEN,"scope denied".into()))}Ok(c)}
fn scope_for(op:&str)->Option<&'static str>{match op{"commander.probe"=>Some("commander:read"),"cloudos.inspect"|"cloudos.git_status"|"cloudos.diff_check"=>Some("cloudos:read"),"cloudos.py_compile"|"cloudos.provider_tests"|"cloudos.full_tests"=>Some("cloudos:test"),_=>None}}
async fn execute(State(state):State<GatewayState>,headers:HeaderMap,Json(req):Json<ExecuteRequest>)->impl IntoResponse{let Some(scope)=scope_for(&req.operation)else{return(StatusCode::FORBIDDEN,Json(serde_json::json!({"error":"unknown operation denied"}))).into_response()};let claims=match authenticate(&headers,&state,scope){Ok(c)=>c,Err((s,e))=>return(s,Json(serde_json::json!({"error":e}))).into_response()};if req.protocol!="KMJ-COMMANDER/1"||Uuid::parse_str(&req.request_id).is_err()||req.nonce.len()<16||req.principal!=claims.sub||req.timestamp.abs_diff(now_secs())>60{return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"error":"invalid request envelope"}))).into_response()}{let mut r=state.replay.lock().unwrap();let now=now_secs();r.retain(|_,exp|*exp>=now);let key=format!("{}:{}:{}",claims.jti,req.request_id,req.nonce);if r.insert(key,claims.exp).is_some(){return(StatusCode::CONFLICT,Json(serde_json::json!({"error":"replayed request"}))).into_response()}}let root=req.root.as_deref().unwrap_or(CLOUDOS_ROOT);let outcome=execute_named(root,&req.operation);let(success,exit_code,output)=match outcome{Ok(v)=>(v.success,v.exit_code,v.output),Err(e)=>(false,None,e)};let digest=output_hash(&output);let event_id=Uuid::new_v4().to_string();let record=AuditRecord{event_id:event_id.clone(),request_id:req.request_id.clone(),timestamp:now_secs(),principal:claims.sub.clone(),server:claims.server.clone(),operation:req.operation.clone(),outcome:if success{"success".into()}else{"failure".into()},exit_code,output_sha256:digest,previous_hash:String::new(),record_hash:String::new()};let ah=match audit::append(&state.audit_path,record){Ok(h)=>h,Err(e)=>return(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"error":format!("audit failure: {e}")}))).into_response()};(if success{StatusCode::OK}else{StatusCode::UNPROCESSABLE_ENTITY},Json(serde_json::to_value(ExecuteResponse{request_id:req.request_id,success,exit_code,output,audit_hash:ah}).unwrap())).into_response()}
async fn audit_log(State(state):State<GatewayState>,headers:HeaderMap)->impl IntoResponse{if let Err((s,e))=authenticate(&headers,&state,"audit:read"){return(s,Json(serde_json::json!({"error":e}))).into_response()}match audit::read_bounded(&state.audit_path,100){Ok(lines)=>(StatusCode::OK,Json(serde_json::json!({"records":lines}))).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"error":e}))).into_response()}}
